/**
 * Contains classes that help facilitate user input captured from an {@link theskidster.xjge.hardware.InputDevice InputDevice} into some action that will be 
 * performed by the object we wish to control. More specifically, the {@link Puppet} component object temporarily couples input events generated by the users input 
 * device to {@link Command} objects supplied by the implementing object. To better understand the relationship between controller and game entity consider how the players 
 * character can be controlled in a side scrolling platformer, the entity has actions (run, jump, etc.) and buttons which correspond to these actions. This process 
 * in essence, is what the classes of this package seek to define.
 * 
 * <p>
 * <b>On object organization:</b><br>
 * Typically objects implementing these utilities are complex and make use of multiple components and other dependencies specific to their functionality. As such, 
 * it is best to confine these objects to their own packages following the structure of the command terminal or freecam objects and provide access to them through 
 * the {@link Puppets} static class. This includes objects that subclass {@link theskidster.xjge.entities.Entity Entity} but only if they also use a puppet object.
 * </p>
 */
package dev.theskidster.xjge.puppets;